### ISSUE TITLE
Bug: System.ArgumentException: An item with the same key has already been added. 

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/Incrementalist#27]
```
fail: Incrementalist[0]
      [GatherAllSlnFiles] - Catastrophic task failure.
System.ArgumentException: An item with the same key has already been added. Key: C:\Repositories\olympus\akka.net\src\benchmark\PingPong\PingPong.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Incrementalist.ProjectSystem.SolutionAnalyzer.AllSolutionFiles(Solution sln, String workingFolder) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\SolutionAnalyzer.cs:line 47
   at Incrementalist.ProjectSystem.Cmds.GatherAllFilesInSolutionCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\GatherAllFilesInSolutionCmd.cs:line 31
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask)
fail: Incrementalist[0]
      [FilterSlnFilesByGitDiff] - Catastrophic task failure.
System.ArgumentException: An item with the same key has already been added. Key: C:\Repositories\olympus\akka.net\src\benchmark\PingPong\PingPong.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Incrementalist.ProjectSystem.SolutionAnalyzer.AllSolutionFiles(Solution sln, String workingFolder) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\SolutionAnalyzer.cs:line 47
   at Incrementalist.ProjectSystem.Cmds.GatherAllFilesInSolutionCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\GatherAllFilesInSolutionCmd.cs:line 31
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask)
   at Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\FilterAffect
```

**Comment by Aaronontheweb** [comment]
Looks like this is the source of the issue: https://github.com/petabridge/Incrementalist/blob/254a6d5455d9257f586f68afe568406c322f629c/src/Incrementalist/ProjectSystem/SolutionAnalyzer.cs#L45-L59
