### ISSUE TITLE
Need to validate the Head branch exist 

### ISSUE THREAD

**Issue by izavala** [petabridge/Incrementalist#28]
C:\Users\user\Documents\GitHub\Baryon (BeginTest -> origin)
λ incrementalist -b dev
fail: Incrementalist[0]
      [FilterSlnFilesByGitDiff] - Catastrophic task failure.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Incrementalist.Git.DiffHelper.ChangedFiles(Repository repo, String targetBranch) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\Git\DiffHelper.cs:line 21
   at Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\FilterAffectedProjectFilesCmd.cs:line 37
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask)
fail: Incrementalist[0]
      [ResolveSlnDependencyGraph] - Catastrophic task failure.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Incrementalist.Git.DiffHelper.ChangedFiles(Repository repo, String targetBranch) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\Git\DiffHelper.cs:line 21
   at Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\FilterAffectedProjectFilesCmd.cs:line 37
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask)
   at Incrementalist.ProjectSystem.Cmds.ComputeDependencyGraphCmd.ProcessImpl(Task`1 previousTask) in C:\Repositories\petabridge\Incrementalist\src\Incrementalist\ProjectSystem\Cmds\ComputeDependencyGraphCmd.cs:line 32
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask)
fail: Incrementalist[0]
      Error encountered during execution of Incrementalist.

C:\Users\user\Documents\GitHub\Baryon (BeginTest -> origin)
λ git branch
* BeginTest
  master

C:\Users\user\Documents\GitHub\Baryon (BeginTest -> origin)

**Comment by izavala** [comment]
When a command is given and the branch does not exist, the above error happens
