### ISSUE TITLE
Bug: NRE during Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/Incrementalist#90]
Version: v0.2.0

Exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd.<>c__DisplayClass3_0.<ProcessImpl>b__4(SlnFileWithPath dependentProject) in D:\a\1\s\src\Incrementalist\ProjectSystem\Cmds\FilterAffectedProjectFilesCmd.cs:line 95
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Incrementalist.ProjectSystem.Cmds.FilterAffectedProjectFilesCmd.ProcessImpl(Task`1 previousTask)
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask) in D:\a\1\s\src\Incrementalist\BuildCommandBase.cs:line 44
   at Incrementalist.ProjectSystem.Cmds.ComputeDependencyGraphCmd.ProcessImpl(Task`1 previousTask) in D:\a\1\s\src\Incrementalist\ProjectSystem\Cmds\ComputeDependencyGraphCmd.cs:line 32
   at Incrementalist.BuildCommandBase`2.Process(Task`1 previousTask) in D:\a\1\s\src\Incrementalist\BuildCommandBase.cs:line 44
   at Incrementalist.Cmd.Commands.EmitDependencyGraphTask.Run() in D:\a\1\s\src\Incrementalist.Cmd\Commands\EmitDependencyGraphTask.cs:line 53
   at Incrementalist.Cmd.Program.ProcessSln(SlnOptions options, String sln, DirectoryInfo workingFolder, MSBuildWorkspace msBuild, ILogger logger) in D:\a\1\s\src\Incrementalist.Cmd\Program.cs:line 160
   at Incrementalist.Cmd.Program.AnaylzeSolutionDIff(SlnOptions options, DirectoryInfo workingFolder, ILogger logger) in D:\a\1\s\src\Incrementalist.Cmd\Program.cs:line 149
   at Incrementalist.Cmd.Program.RunIncrementalist(SlnOptions options) in D:\a\1\s\src\Incrementalist.Cmd\Program.cs:line 122
Running build failed.

```

Occurred here in the[akka.net](https://github.com/akkadotnet/akka.net) project:

https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=24771&view=logs&jobId=59d8d678-3f9b-55ef-c67e-99309e0aad31&j=59d8d678-3f9b-55ef-c67e-99309e0aad31&t=19c42ae4-c1cb-54a8-7704-e3755eb51343

**Comment by IgorFedchenko** [comment]
Here is the throwing line:
```csharp
projectImports[file].DependantProjects.ForEach(dependentProject => newDict[dependentProject.Path] = dependentProject.File);
```

And this is throwing lambda function from stacktrace:
```csharp
dependentProject => newDict[dependentProject.Path] = dependentProject.File
```

`newDict` can not be null, and `[]` operations throws `ArgumentException` on null, so the only case when we can get NRE is `dependendProject` is `null`.

But I just can not understand how `null` value get's there... There is only one suspicious place, where I do populate  `DependantProjects` collection, but I do not see how `null` value could be inserted...

I will add PR with some cleanup in that suspicious  place, and will see if this can be reproduced again.
